management:
  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

spring:
  application:
    name: post-service

server:
  port: 8080

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"