global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "spring-post-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: "spring-comment-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]